### ISSUE TITLE
Implement D_XY datatype

### ISSUE THREAD

**Issue by phako** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#13]
The server I am porting does a lot of its data visualization through D_XY datatype

https://ttfinfo.desy.de/DOOCSWiki/Wiki.jsp?page=C%2B%2B%20Server%20Interface#section-C_2B_2B+Server+Interface-D_xyClass

It basically needs two float arrays that are mapped to the respective plot axes. The consistency of the two arrays is crucial here, i.e. it is needed to make sure that the two arrays are written "on the same time"

**Comment by mhier** [comment]
Dependency for the guarantee of consistency is: ChimeraTK/DeviceAccess#25
