### ISSUE TITLE
Attach macro pulse number and time stamp to all data

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#15]
Use D_fct::set_mpnum() and D_fct::set_tmstmp() to set the macro pulse number and the time stamp for all properties (don't forget to use D_fct::set_stamp(1)). The implementation can be similar to #12. If #14 is already done, make sure that data consistency is guaranteed in the same way.

**Comment by killenb** [comment]
@mhier,Seems this was implemented in 29aac36a. Please confirm and close this ticket if correct.

**Comment by d-rothe** [comment]
should be fixed, if it was not yet, after refactoring #81
