### ISSUE TITLE
Race condition with ZeroMQ publishing

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#20]
serverTestZeroMQ spuriously fails. It first needs to be be investigated whether this is a real issue or just a bug in the test. It seems rather likely it is a test issue, but still it should be fixed.

**Comment by vargheseg** [comment]
Status:
Was not able to reproduce this ticket; also could not observe this test failing spuriously in existing Jenkins builds at the time this was postponed.

Need feedback on if the tests still keep failing and needs fixing.

**Comment by mhier** [comment]
Close, seems to have disappeared.
