### ISSUE TITLE
Allow overriding data type of properties

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#21]
For arrays, the data type can be overridden. The same feature should be implemented for scalar properties.

This ticket is urgent, since this feature is required for the LLRF server moving to ChimeraTK. Deadline is the 12th of April 2019.

**Comment by mhier** [comment]
Is there already any documentation about this new feature?

**Comment by phako** [comment]
Ah. No. Good point.
