### ISSUE TITLE
ZeroMQ sending for CS to App variables

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#23]
ZeroMQ can already be enabled also for ControlSystem to Application variables. New values which are input from the ControlSystem should be sent to subscribers. This can be useful e.g. if two servers share certain settings, so the user has to punch in the numbers only once and the first server distributes the values to the second.

**Comment by mhier** [comment]
This is required for the diagnostic server and the trip event logger!

**Comment by vargheseg** [comment]
We now publish value changes made from the Doocs system to all zmq subscribers. This feature is supported for:                                                                                                                                                                                                                                                                                   
- DoocsSpectrum                                                                                                                                                                                                                                                                                                               
- DoocsIfff                                                                                                                                                                                                                                                                                                                   
- DoocsProcessArray                                                                                                                                                                                                                                                                                                           
- DoocsProcessScalar                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                              
See commit fec836353afc7bb159af051305cf00c39250d7de

**Comment by vargheseg** [comment]
Ticket https://github.com/ChimeraTK/ControlSystemAdapter-DoocsAdapter/issues/61 tracks test coverage.
