### ISSUE TITLE
ZeroMQ sending without specified macro pulse number source might crash

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#25]
In some situations, enabling ZMQ publication while not specifying the macro pulse number source might run into a share_ptr assertion in DoocsProcessScalar::updateDoocsBuffer() when the _macroPulseNumberSource is dereferenced. It seems to happen in certain configurations always and in other configurations never. Further investigation is required.

**Comment by vargheseg** [comment]
Summary of the two approaches discussed for this problem:
1. Make macroPulseNumberSource a hard constraint; logic_error if not set.
2. Decide on a good default value for `dmsg_info.ident` when   _macroPulseNumberSource is a nullptr:
    ~~~.cpp
      if(_publishZMQ) {
        ...
        info.ident = (_macroPulseNumberSource)
                         ? _macroPulseNumberSource->accessData(0)
                         : default_value;
        ...
      }
    ~~~

Not sure which way to go at this point.

**Comment by d-rothe** [comment]
crash should not happen after recent refactoring #81 so closing this.
