### ISSUE TITLE
Update XSD schema for D_xy and variable types

### ISSUE THREAD

**Issue by phako** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#27]
The XML format has been extended but I forgot to extend the XSD file to reflect those changes

**Comment by killenb** [comment]
I thought I put a test that checks all example and test xml files against the schema. But this somehow did not catch it. Either I forgot to put the test, or the search pattern missed the file. Please check that such a test is there.

**Comment by phako** [comment]
It only check the XML files under tests/variableTreeXml but not the XML files from the tests

**Comment by d-rothe** [comment]
closing this because XSD was extended/fixed some time ago. However, it's not really used anywhere from automatic tests, only by manual call of xml_shema_validation.sh
