### ISSUE TITLE
Handle data fault flags

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#28]
This ticket is a child of ChimeraTK/ApplicationCore#10 and depends on ChimeraTK/ControlSystemAdapter#18.

The data fault flag has been introduced in ChimeraTK/ControlSystemAdapter#18. If the adapter receives a variable from the application which has the flag set, it should set the DOOCS error status on that variable. This should be possible with D_fct::d_error().

- [ ] Implementation
- [ ] Test

**Comment by phako** [comment]
The appropriate error flag might be "stale_data".
