### ISSUE TITLE
referenceTestDoocsServer crash: boost::thread_resource_error

### ISSUE THREAD

**Issue by vargheseg** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#3]
referenceTestDoocsServer crashes with the following log:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
  what():  boost::thread_resource_error: Resource temporarily unavailable
Aborted (core dumped)
```

This was observed a few minutes after keeping the server alive.

**Comment by killenb** [comment]
Is this ticket still relevant? Jenkins is not reporting any issues and the ticket is more than two years old now.

**Comment by vargheseg** [comment]
Don't think this is relevant as mentioned. AFAIK did not see this reoccur.
