### ISSUE TITLE
Regression: string properties broken

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#31]
Application-to-controlsystem strings are no longer propagating its values into DOOCS. They just keep the last value from the DOOCS conf file. This must be a regression introduced in one of the last releases. It was for sure working in 00.10.00.

**Comment by phako** [comment]
I cannot reproduce this. I have added some string property tests to the DoocsAdapter and also checked with a "normal" ApplicationCore-based server.
