### ISSUE TITLE
Allow to set the EqFct code in mapping file 

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#4]
It should be possible to specify the code of the EqFct (as returned by `EqFct::fct_code()`) in the `<location>` tag of the mapping file. ~~If the code is specified, the name shall be optional and shall be taken from the DOOCS config file (in which case the location code has to be unique within this server).~~

~~This allows to set the names in only one single point (the DOOCS config file) and makes the mapping file independent of e.g. the station name (which is usually part of all location names).~~ (This is no longer necessary, since locations missing in the config file are automatically added.) In addition it may be useful for the watchdog, which tries to find generic panels through the location code.

**Comment by killenb** [comment]
Merged into master and tagged as 00.12.00. Closing the ticket.
