### ISSUE TITLE
Data with "invalid" flag should not be archived

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#40]
Data which has the "data invalid" flag set should not be written to the history. The data probably is not filtered by the history filter because it might be all over the place, which lets the size of the history grow quickly (and this with useless data).

Wanted behaviour:
* For the first invalid data that is published, set_and_archive() is called with the last valid published data point plus "data invalid flag". Like this the colour in the history can change to indicate the time when there was no valid data. After this call set_value() (without archive) with the invalid data value (plus setting the invalid flag)
* For all following invalid data points the value is published via set_value() (plus invalid flag), but not written to the history.
* If a valid data point arrives, it is written with set_and_archive(), as usual.

Publishing invalid data makes sense for "live" tracking. The data might for instance be very noisy (e.g. phase calculated from I and Q for small amplitudes). In this case the data is roughly correct (e.g. 80 +- 10) which shows that it is in the correct range, but for normal operation the history filter is set to +- 2, so the history file is would be growing rapidly if archived.

In case the data invalid flag is not published at all yet, this will automatically be part of this ticket.

**Comment by toseko** [comment]
After discussion with Martin H., we decided to implement ticket in a little bit different manner.
First data marked as invalid is stored in history as it is (the value), but error flag is passed to set_and_archive(). Rest of invalid data is not stored in the history (set_value() is used). Ticket as described leads to the issue that old data is presented to external world as current one, only with invalid flag. First of all not all clients must check validity flag. Moreover,  this also may lead to confusion when value which seems to be OK is presented as invalid. All users would need to know that this kind of "hack" is done.

**Comment by toseko** [comment]
Just forgot to mention. The feature was manually tested by setting validity flag in application and adding additional printouts to test if internal state of object is as expected. It showed that logic behave correctly. First invalid value is stored with set_and_archive and invalid status to the doocs archiver. Rest of invalid data is send to doocs with set_value method.
