### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#42]
We should not only flag individual properties with errors but also report errors to the DOOCS status flags. How this works is documented here:

https://ttfinfo.desy.de/DOOCSelog/show.jsp?dir=/2019/10&pos=2019-10-18T15:17:55

I think we should report both device exceptions and application-defined errors (e.g. defined by the StatusMonitor/StatusAggregator ApplicationCore modules) through this mechanism. The error status will then be present in the DOOCS watchdog and is being aggregated on a per-cpu level. It is (or will be) then also shown on the relevant panels in the control system and even on overall status displays (like the big screens in the control room).

**Comment by d-rothe** [comment]
Moved to here: https://redmine.msktools.desy.de/issues/9838
