### ISSUE TITLE
Support for IFFF data type

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#45]
Follow the example of of the `DoocsXy` class, which creates a `D_xy`. In a similar fashion, write a new class `DoocsIfff`, which crates a `D_ifff`. Instead of having two process variables, now four process variables are required: on integer and three float scalars.

Besides the DoocsIfff class, also a function `DoocsPVFactory::createIfff()` is needed (see `DoocsPVFactory::createXy()` for reference). This function needs to be called in `DoocsPVFactory::create()`.

Also a struct `IfffDescription` (see `XyDescription` for reference) needs to be created. Unike in `XyDescription`, there is no axis, but the 4 sources need to be defined.

To fill this struct, a function `VariableMapper::processIfffNode()` (see `VariableMapper::processXyNode()` for reference) needs to be written. This function needs to obtain the information about the 4 sources from the XML variable mapping file.

Write a test similar to `serverTestXy.cpp`. You will need to create a variable mapping file forming a IFFF type from the available variables in the reference test application.

DOOCS documentation for the D_ifff:
https://ttfinfo.desy.de/DOOCSWiki/Wiki.jsp?page=C%2B%2B%20Server%20Interface#section-C_2B_2B+Server+Interface-D_ifffClass

**Comment by killenb** [comment]
Should the three integers come from an array or should they be individual variables?

**Comment by mhier** [comment]
I would say they should be individual variables. I am not sure if this fits with the use case in the diagnostic server, though... (In the long run one might consider having both options, right now I would only implement what is currently needed.)

**Comment by killenb** [comment]
Status when handing over the ticket

* XML part should be ok, only basic app->CS tested
* Instantiation with factory working
* app->CS
  * Basic implementation is running, incl. test
    * Still missing: Correlation with macro pulse number
    * Still missing: sending via ZMQ
    * Still missing: second constructor without history
    * Still missing: test of the history
* CS->App
  * Basic implementation is hacked in. Compiles but not tested
  * Still missing: correlation with macro pulse number

Everything that is in the original ticket is in, but XY does not have history, ZMQ and CS->app, and it is missing the correlation with the macro pulse number.

**Comment by vargheseg** [comment]
The following has been done:
- Added support for macropulse source.
- zmq publication of IFFF property.
- Manually tested IFFF:
   - zmq publication
   - application -> control_system communication
   - control_system -> application communication

Pending:
Automated tests for all the manual tests above (+ history).
