### ISSUE TITLE
DoocsXy is missing macor pulse number

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#46]
The Doocs adapter does not set the macropulse number for the D_xy it publishes.

Can D_xy be send via ZMQ? If yes, this is also missing.

**Comment by mhier** [comment]
Macropulse number should always be set. In case of ZeroMQ it needs to be set twice, once in the EqData buffer, another time in the ZeroMQ header.

**Comment by d-rothe** [comment]
Fixed with recent refactoring #81
