### ISSUE TITLE
Check TSAN/ASAN errors currently being suppressed

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#54]
The suppressions file JenkinsConfiguration/sanitizer.suppressions/tsan-doocs.supp and .../asan-doocs.supp suppresses several known issues coming from DOOCS. Some of them have been reported to the DOOCS developers and they should be checked whether they have been fixed. Others are not yet properly understood, they need to be properly investigated.

Note: It might be necessary to get DOOCS fully compiled with tsan/asan flags enabled for the further investigation.

**Comment by mhier** [comment]
According to the DOOCS RT ticket (https://rt-system.desy.de/Ticket/Display.html?id=984864) the reported issues has been resolved. Please make sure the TSAN/ASAN errors are really gone (DOOCS people probably had to rely on my suggested fix). If yes, remove them from the suppressions file. Otherwise re-report them to DOOCS RT with additional information.

**Comment by phako** [comment]
Unfortunately RT tickets are (at least by default) not visible to other people than the reporter and the queue owner

**Comment by mhier** [comment]
The ticket says it's done.

**Comment by mhier** [comment]
They seem to have done something, but TSAN is still reporting thread leaks...
