### ISSUE TITLE
Properties mapped on the same variable are not synchronised

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#7]
When mapping multiple DOOCS properties on the same process variable (in the direction control system to device), the different DOOCS properties are not synchronised to each other. When changing the value of the variable through one of the properties, the other properties keep their current values. This can be avoided and shouldn't lead to (real) race conditions, since on the DOOCS side locks can be used.

**Comment by d-rothe** [comment]
was implemented in #75
